version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      # - db:/data/db
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./dump:/dump
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    env_file: ./.env
    ports:
      - 8081:8081
    depends_on:
      - server
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=mongodb
      
  server:
    container_name: server
    depends_on:
      - mongodb
    image: server-binotify-rest:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET=$JWT_SECRET
      - DB_HOST=mongodb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=27017
    stdin_open: true
    tty: true

# volumes:
#   db: