version: '3.8'

services:
  server:
    container_name: server-binotify-rest
    image: server-binotify-rest:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app

    ports:
       - 3000:3000

    extra_hosts:
      - "host.docker.internal:host-gateway"
  
networks:
  binotify-config_some-net:
    external: true
  

