version: '3.8'

services:
  server:
    container_name: server-binotify-rest
    image: server-binotify-rest:latest
    build:
      context: .
      dockerfile: server.Dockerfile
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    depends_on:
      - db